name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Build and Generate Artifacts
      run: |
        # Compile the source code and generate artifacts
        
  test:
    needs: build
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Run Tests and Code Quality Checks
      run: |
        # Run unit tests and code quality checks here
        
  deploy:
    needs: test
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

      
      
    - name: Deploy to Staging
      run: |
        # Deploy the application to a staging environment

        - name: Notify on Failure

          if: failure()

             uses: actions/github-script@v0.9.0

             with:
               script: |
                const issueTitle = 'Deployment Failed';
                const issueBody = 'There was a failure in deploying.';
                github.issues.create({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  title: issueTitle,
                  body: issueBody
                  });





